---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-2
spec:
  storageClassName: datanode-pv-2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata/datanodedata-2
    server: 10.221.163.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-hadoop-hdfs-datanode-2
spec:
  storageClassName: datanode-pv-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
