---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: journalnode-pv-1
spec:
  storageClassName: journalnode-pv-1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata/journalnodedata-1
    server: 10.221.163.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-hadoop-hdfs-journalnode-1
spec:
  storageClassName: journalnode-pv-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
