---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv-standby
spec:
  storageClassName: namenode-pv-standby
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata/namenodedata-standby
    server: 10.221.163.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-hadoop-hdfs-namenode-1
spec:
  storageClassName: namenode-pv-standby
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
