---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storm-master-pv
spec:
  storageClassName: storm-master-pv
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/storm-master
    server: 10.221.163.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-storm-master-0
spec:
  storageClassName: storm-master-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
