---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storm-slave-pv-2
spec:
  storageClassName: storm-slave-pv-2
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/storm-2
    server: 10.221.163.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-storm-slave-2
spec:
  storageClassName: storm-slave-pv-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi