---
kind: Service
apiVersion: v1
metadata:
  name: spark-master-headless
  labels:
    app: spark
    component: spark-master
spec:
  ports:
  - name: server
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: web-http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: spark
    component: spark-master
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
