---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster2-journalnode-pv-2
spec:
  storageClassName: cluster2-journalnode-pv-2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/journalnodedata-2
    server: 10.221.163.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-cluster2-hdfs-journalnode-2
spec:
  storageClassName: cluster2-journalnode-pv-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
