---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster2-namenode-pv-master
spec:
  storageClassName: cluster2-namenode-pv-master
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/namenodedata-master
    server: 10.221.163.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-cluster2-hdfs-namenode-0
spec:
  storageClassName: cluster2-namenode-pv-master
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
