---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/spark/spark-master
    server: 10.221.105.240
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-spark-master-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
