---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-slave-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/spark/spark-slave-1
    server: 10.221.105.240
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-spark-slave-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi