---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster2-namenode-pv-standby
spec:
  storageClassName: cluster2-namenode-pv-standby
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/namenodedata-standby
    server: 10.221.163.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-cluster2-hdfs-namenode-1
spec:
  storageClassName: cluster2-namenode-pv-standby
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
