---
kind: Service
apiVersion: v1
metadata:
  name: spark-master-service
  labels:
    app: spark
    component: spark-master
spec:
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8082
    nodePort: 31082
  selector:
    app: spark
    component: spark-master
  type: NodePort
  sessionAffinity: None
