---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodemanager-pv-2
spec:
  storageClassName: nodemanager-pv-2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata/nodemanagerdata-2
    server: 10.221.163.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-second-hdfs-nodemanager-2
spec:
  storageClassName: nodemanager-pv-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
