---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-2
spec:
  storageClassName: zk-pv-2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/zkdata/zk-2
    server: 10.221.163.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zookeeper-cluster-2
spec:
  storageClassName: zk-pv-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
