---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-1
spec:
  storageClassName: zk-pv-1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/zkdata/zk-1
    server: 10.221.163.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zookeeper-cluster-1
spec:
  storageClassName: zk-pv-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
