---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-pv
spec:
  storageClassName: spark-master-pv
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/hadoopdata-cluster2/spark-master
    server: 10.221.163.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-spark-master-0
spec:
  storageClassName: spark-master-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
