---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: cluster2-hdfs-resourcemanager
  labels:
    app: hadoop
    component: hadoop-resourcemanager
    cluster: cluster2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hadoop
      component: hadoop-resourcemanager
      cluster: cluster2
  template:
    metadata:
      labels:
        app: hadoop
        component: hadoop-resourcemanager
        cluster: cluster2
    spec:
      volumes:
      - name: hdfs-config
        configMap:
          name: cluster2-hdfs-configmap
          defaultMode: 420
      - name: rm-config
        configMap:
          name: cluster2-rm-configmap
          defaultMode: 420 
      containers:
      - name: cluster2-resourcemanager
        image: 10.221.163.21:5000/hadoop-hh:1
        command:
        - "/bin/bash"
        - "/etc/hadoop-config/bootstrap.sh"
        - "-d"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: manager
          containerPort: 8032
          protocol: TCP
        - name: scheduler
          containerPort: 8030
          protocol: TCP
        - name: tracker
          containerPort: 8031
          protocol: TCP 
        - name: admin
          containerPort: 8033
          protocol: TCP   
        - name: http
          containerPort: 8088
          protocol: TCP       
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
        volumeMounts:
        - name: hdfs-config
          mountPath: "/tmp/hadoop/hdfs" 
        - name: rm-config
          mountPath: "/tmp/hadoop/resourcemanager"
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "/etc/hadoop-config/healthcheck-resourcemanager.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "/etc/hadoop-config/healthcheck-resourcemanager.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3            
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      ### podAntiAffinity 描述pod被调度的策略
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: hadoop
                  component: hadoop-resourcemanager
                  cluster: cluster2
              topologyKey: kubernetes.io/hostname           
      schedulerName: default-scheduler
  serviceName: cluster2-resourcemanager-headless
  podManagementPolicy: OrderedReady
