---
kind: Service
apiVersion: v1
metadata:
  name: storm-master-service
  labels:
    app: storm
    component: storm-master
spec:
  ports:
  - name: webstorm
    protocol: TCP
    port: 8087
    targetPort: 8087
    nodePort: 30081
  selector:
    app: storm
    component: storm-master
  type: NodePort
  sessionAffinity: None
