---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: storm-master
  labels:
    app: storm
    component: storm-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storm
      component: storm-master
  template:
    metadata:
      labels:
        app: storm
        component: storm-master
    spec:
      containers:
      - name: storm-master
        image: 10.221.163.21:5000/storm:1
        command:
        - "/bin/bash"
        - "/etc/storm-config/start-master.sh"
        - "-d"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: server1
          containerPort: 6700
          protocol: TCP
        - name: server2
          containerPort: 6701
          protocol: TCP
        - name: server3
          containerPort: 6702
          protocol: TCP
        - name: server4
          containerPort: 6703
          protocol: TCP
        - name: server5
          containerPort: 6704
          protocol: TCP
        - name: webstorm
          containerPort: 8087
          protocol: TCP
        volumeMounts:
        - name: datadir
          mountPath: "/usr/local/apache-storm-1.1.0/data"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 200Mi    
  serviceName: storm-master-headless
  podManagementPolicy: OrderedReady
